# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-28 12:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20171028_1202'),
    ]

    operations = [
        migrations.CreateModel(
            name='KategoriArtikel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategori', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='artikel',
            name='kategori',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='blog.KategoriArtikel'),
            preserve_default=False,
        ),
    ]
