# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-29 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20171028_1206'),
    ]

    operations = [
        migrations.CreateModel(
            name='Berita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=300)),
                ('gambar', models.FileField(upload_to='static/blog/gambar/')),
                ('tanggal', models.DateField()),
                ('isi', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='artikel',
            name='gambar',
            field=models.FileField(upload_to='static/blog/gambar/'),
        ),
    ]
