# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-30 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20171029_0953'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=300)),
                ('gambar', models.FileField(upload_to='static/berita/gambar/')),
                ('tanggal', models.DateField()),
                ('isi', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='berita',
            name='gambar',
            field=models.FileField(upload_to='static/berita/gambar/'),
        ),
    ]
