# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-04 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departemen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_departemen', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pelajar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lengkap', models.CharField(max_length=100)),
                ('alamat', models.CharField(max_length=100)),
                ('tanggal_lahir', models.DateField()),
                ('foto', models.FileField(upload_to='static/pelajar/foto')),
            ],
        ),
    ]
