# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-04 11:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pelajar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organisasi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_organisasi', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='pelajar',
            name='departemen',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='pelajar.Departemen'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='departemen',
            name='organisasi',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='pelajar.Organisasi'),
            preserve_default=False,
        ),
    ]
